In [1]:
import torch
import numpy as np
import pandas as pd

In [2]:
x=pd.read_csv('../chess/games.csv')

In [3]:
x.shape

(20058, 16)

In [4]:
x.head()

id  rated    created_at  last_move_at  turns victory_status winner  \
0  TZJHLljE  False  1.504210e+12  1.504210e+12     13      outoftime  white   
1  l1NXvwaE   True  1.504130e+12  1.504130e+12     16         resign  black   
2  mIICvQHh   True  1.504130e+12  1.504130e+12     61           mate  white   
3  kWKvrqYL   True  1.504110e+12  1.504110e+12     61           mate  white   
4  9tXo1AUZ   True  1.504030e+12  1.504030e+12     95           mate  white   

  increment_code       white_id  white_rating      black_id  black_rating  \
0           15+2       bourgris          1500          a-00          1191   
1           5+10           a-00          1322     skinnerua          1261   
2           5+10         ischia          1496          a-00          1500   
3           20+0  daniamurashov          1439  adivanov2009          1454   
4           30+3      nik221107          1523  adivanov2009          1469   

                                               moves opening_eco  \
0  d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...         D10   
1  d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...         B00   
2  e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...         C20   
3  d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...         D02   
4  e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...         C41   

                             opening_name  opening_ply  
0        Slav Defense: Exchange Variation            5  
1  Nimzowitsch Defense: Kennedy Variation            4  
2   King's Pawn Game: Leonardis Variation            3  
3  Queen's Pawn Game: Zukertort Variation            3  
4                        Philidor Defense            5

In [5]:
xn=np.asarray(x)

In [6]:
myx=xn[:,[5,6,9,11,12]]

In [7]:
myx=myx[np.where(myx[:,0]=='mate')]

In [11]:
print(myx[0])

['mate' 'white' 1496 1500
 'e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc6 bxc6 Ra6 Nc4 a4 c3 a3 Nxa3 Rxa3 Rxa3 c4 dxc4 d5 cxd5 Qxd5 exd5 Be6 Ra8+ Ke7 Bc5+ Kf6 Bxf8 Kg6 Bxg7 Kxg7 dxe6 Kh6 exf7 Nf6 Rxh8 Nh5 Bxh5 Kg5 Rxh7 Kf5 Qf3+ Ke6 Bg4+ Kd6 Rh6+ Kc5 Qe3+ Kb5 c4+ Kb4 Qc3+ Ka4 Bd1#']


In [12]:
print(myx.shape)
print(np.max(myx[:,[2,3]]))
print(np.min(myx[:,[2,3]]))
print(np.mean(myx[:,[2,3]]))

(6325, 5)
2621
784
1526.3966798418971


In [13]:
x2=myx[np.where(myx[:,2:3]>=2000)[0]]

In [69]:
x2.savetxt('../chess/x2000.csv')

AttributeError: 'numpy.ndarray' object has no attribute 'savetxt'

In [14]:
x2=np.asarray(x2)

In [15]:
x2=x2[:,1:5]

In [16]:
x2[0]

array(['white', 2436, 978,
       'e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6 Be3 Bg7 f3 O-O Qd2 Nc6 Bc4 Be6 Bxe6 Nxd4 Bxf7+ Rxf7 Bxd4 d5 e5 Ne8 e6 Rf8 O-O-O Bxd4 Qxd4 Qa5 Nxd5 Rc8 Nxe7#'],
      dtype=object)

In [17]:
x2[x2=='white']=0
x2[x2=='black']=1

In [18]:
chess_str=x2[0][3]
print(chess_str)

e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6 Be3 Bg7 f3 O-O Qd2 Nc6 Bc4 Be6 Bxe6 Nxd4 Bxf7+ Rxf7 Bxd4 d5 e5 Ne8 e6 Rf8 O-O-O Bxd4 Qxd4 Qa5 Nxd5 Rc8 Nxe7#


In [19]:
board=np.zeros(64).reshape(8,8)

In [20]:
board[1]=1
board

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
board[6]=1
board

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
piece_dict =	{
  "empty": 0,
  "pawn": 1,
  "knight": 2,
  "bishop": 3,
  "rook": 4,
  "queen": 5,
  "king": 6,
}
print(piece_dict)

{'empty': 0, 'pawn': 1, 'knight': 2, 'bishop': 3, 'rook': 4, 'queen': 5, 'king': 6}


In [23]:
piece_dict['empty']

0

In [24]:
board[0,[0,7]]=piece_dict['rook']
board[7,[0,7]]=piece_dict['rook']
board[0,[1,6]]=piece_dict['knight']
board[7,[1,6]]=piece_dict['knight']
board[0,[2,5]]=piece_dict['bishop']
board[7,[2,5]]=piece_dict['bishop']
board[[0,7],3]=piece_dict['queen']
board[[0,7],4]=piece_dict['king']
board

array([[4., 2., 3., 5., 6., 3., 2., 4.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [4., 2., 3., 5., 6., 3., 2., 4.]])

In [25]:
bcolour=np.zeros(64).reshape(8,8)
bcolour[0:2]=2
bcolour[6:8]=1
bcolour

array([[2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [26]:
fboard=np.asarray([board,bcolour])


In [27]:
mlist=chess_str.split(' ')

In [28]:
fboard

array([[[4., 2., 3., 5., 6., 3., 2., 4.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [4., 2., 3., 5., 6., 3., 2., 4.]],

       [[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [126]:
len(mlist[0])

2

In [129]:
move=mlist[0]
move

'e4'

In [135]:
def move_coords(move):
    coor_dict =  {
        'a':0,
        'b':1,
        'c':2,
        'd':3,
        'e':4,
        'f':5,
        'g':6,
        'h':7
    }
    x=8-int(move[1])
    y=coor_dict[move[0]]
    return x,y

In [139]:
game1=fboard
game1

array([[[4., 2., 3., 5., 6., 3., 2., 4.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [4., 2., 3., 5., 6., 3., 2., 4.]],

       [[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [53]:
class Pawn(Piece):
    def __init__(self,x,y,colour):
        super().__init__(x,y,colour)
    
    def moves(self):
        moves=[(self.x,self.y+1),(self.x,self.y+2)]
        return moves



In [52]:
class Piece:
    def __init__(self,x,y,colour):
        self.x=x
        self.y=y
        self.colour=colour
    def make_move(self,board,x,y):
        board[:,self.x,self.y]=0
        board[:,x,y]=self
        

In [55]:
p1=Pawn(0,0,0)

In [56]:
p1.make_move(fboard,1,1)

TypeError: float() argument must be a string or a number, not 'Pawn'